apiVersion: v1
kind: Service
metadata:
  name: express-kafka-service
  labels:
    app: express-angular-kafka
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
      targetPort: 3000
  selector:
    app: express-angular-kafka
    tier: backend
  clusterIP: 10.100.222.47
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-kafka
spec:
  selector:
    matchLabels:
      app: express-angular-kafka
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: express-angular-kafka
        tier: backend
    spec:
      containers:
        - name: express-kafka
          image: mawfia/swe645a4-express:{{ .Values.version | default 1.0 }}
          ports:
            - name: express
              containerPort: 3000
